version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: agri_blazorapp
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./postgres.env

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres_data: